#!/bin/bash
#
# Photostudio TikTok Content Generator
# Creates ready-to-post TikTok scripts + concepts
#

set -e

DATE=$1
OUTPUT_DIR=$2

OUTPUT_FILE="$OUTPUT_DIR/photostudio-tiktok-$DATE.md"
VIDEO_CONCEPTS_FILE="$OUTPUT_DIR/photostudio-video-concepts-$DATE.json"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

log "  📸 Generating Photostudio TikTok content..."

# Generate 5 TikTok script concepts
cat > "$OUTPUT_FILE" << 'EOF'
# 📸 Photostudio.io - TikTok Content Pack
*Autogenerated - Ready to film or use as reference*

---

## 🎯 Content Strategy

**Target Audience:**
- E-commerce store owners (fashion, apparel)
- Product photographers
- Small brands needing visuals
- Dropshippers

**Value Proposition:**
- Save money (no photoshoots needed)
- Save time (instant outputs)
- Professional quality (e-commerce ready)
- Consistency (same item, multiple uses)

**Content Pillars:**
1. **Transformation** - Before/after reveals
2. **Money savings** - Cost comparisons
3. **Time savings** - Speed demonstrations
4. **Quality showcase** - Professional results
5. **Education** - How it works

---

## 🎬 Video Concept 1: The "Wait, What?" Hook

**Hook (0-3 seconds):**
"Watch this dress transform into 5 professional product photos in seconds..."

**Visual:**
- Fast montage: Original photo → Ghost mannequin → Flatlay → On-model → Lifestyle

**Caption:**
"POV: You just saved €2,000 on your product photoshoot 📸

✨ One photo, unlimited possibilities
✨ E-commerce quality, instant delivery
✨ No photographer, no studio, no stress

Which output would YOU use for your store?

#productphotography #ecommerce #fashion #ai #smallbusiness"

**Audio Suggestion:**
- Trending sound with upbeat tempo
- Or: Voiceover with "Wait, what? Did you see that?"

**Expected Performance:**
- High virality potential (visual wow factor)
- Good for brand awareness
- Target: e-commerce owners, fashion brands

---

## 🎬 Video Concept 2: The Money Comparison

**Hook (0-3 seconds):**
"Traditional photoshoot: €3,500. Photostudio: €35. Guess which one this is..."

**Visual:**
- Side-by-side comparison
- Left: Studio setup (lights, camera, photographer, model, rack of clothes)
- Right: Single upload on laptop
- Both showing final professional result

**Caption:**
"Traditional photoshoot vs. Photostudio.io 💸

❌ Traditional: €3,500+
   - Photographer: €1,200
   - Model: €800
   - Studio rental: €600
   - Setup time: 6 hours
   - Revision: +€400

✅ Photostudio: €35
   - AI processing: instant
   - Unlimited revisions: included
   - 5 output formats: included
   - Delivery: seconds

Result? Same quality. 1% of the cost.

Smart brands choose Photostudio 🧠

#productphotos #ecommerce #save #budget #smartbusiness"

**Audio Suggestion:**
- "Price Tag" by Jessie J (instrumental)
- Or: Money sound effects

**Expected Performance:**
- Strong for business owners
- High save rate (value proposition)
- Good for conversions

---

## 🎬 Video Concept 3: The Time-Lapse

**Hook (0-3 seconds):**
"What takes 3 days in a studio... we do in 30 seconds. Watch."

**Visual:**
- Split screen time-lapse
- Top: Traditional shoot (setting up lights, styling, shooting, editing)
- Bottom: Upload bar completes → 5 final images appear
- Timestamps showing 3 days vs 30 seconds

**Caption:**
"3 days vs. 30 seconds. Same result. 🤯

Traditional photoshoot timeline:
• Day 1: Setup & prep (6 hours)
• Day 2: Photoshoot (8 hours)
• Day 3: Editing & delivery (24 hours)
• Revision: +2 days

Photostudio timeline:
• Upload: 2 seconds
• AI processing: 25 seconds
• 5 formats delivered: Instant
• Unlimited revisions: Included

Launch your collection FASTER.

#productlaunch #fashion #speed #ecommerce #automation"

**Audio Suggestion:**
- Fast-paced, energetic music
- Clock ticking sound effects

**Expected Performance:**
- Appeals to time-poor entrepreneurs
- Strong differentiation message
- Good for fashion brands launching collections

---

## 🎬 Video Concept 4: The Quality Showcase

**Hook (0-3 seconds):**
"People think AI photos look fake... until they see this."

**Visual:**
- Zoom into extreme close-up of fabric texture
- Show lighting quality
- Show color accuracy
- Reveal: "This is AI-generated"

**Caption:**
"The AI quality myth... BUSTED 💥

✅ Crisp detail (zoom in, no pixelation)
✅ Perfect lighting (studio-quality shadows)
✅ True-to-life colors (color-accurate)
✅ Consistent across all formats

This isn't 'good enough for AI'...
This is GOOD ENOUGH FOR YOUR STORE.

Don't compromise on quality. Don't overpay for photos.

Photostudio.io - Professional product visuals, instant.

#quality #productphotography #ai #fashion #ecommerce #professional"

**Audio Suggestion:**
- Myth-busting sound effect
- Clean, professional audio

**Expected Performance:**
- Addresses objections (AI quality concerns)
- Trust-building content
- High conversion potential

---

## 🎬 Video Concept 5: The "Behind the Scenes"

**Hook (0-3 seconds):**
"Here's how we turn ONE photo into FIVE professional outputs..."

**Visual:**
- Screen recording of the actual process
- Show the upload
- Show options being selected
- Show all 5 outputs appearing
- Speed ramp for dramatic effect

**Caption:**
"Behind the scenes at Photostudio.io 🎬

One photo → 5 professional outputs:

1️⃣ Ghost Mannequin (clean, floating look)
2️⃣ Flatlay (catalog standard)
3️⃣ On-model (lifestyle appeal)
4️⃣ Lifestyle (context & atmosphere)
5️⃣ Video (coming soon!)

All from ONE upload. All consistent quality. All instantly.

Want to see it work with YOUR products?

Comment 'DEMO' and we'll show you!

#howitsmade #productphotography #ecommerce #fashion #behindthescenes"

**Audio Suggestion:**
- Educational, friendly tone
- Background music: Lo-fi or chill

**Expected Performance:**
- Educational content builds trust
- Generates engagement (comment 'DEMO')
- Lead generation opportunity

---

## 📊 Posting Schedule

**Recommended:**
- Post 1-2 times per day
- Mix between hooks (transformation, money, time, quality)
- Test variations of each concept
- Track analytics, double down on winners

**Best Times:**
- Morning: 8-10 AM (business owners planning day)
- Lunch: 12-2 PM (scrolling while eating)
- Evening: 7-9 PM (relaxing, planning tomorrow)

**Hashtag Mix:**
- Broad: #ecommerce #productphotography #fashion
- Niche: #ghostmannequin #flatlay #productphotos
- Business: #smallbusiness #entrepreneur #ecommercetips
- Trending: Check TikTok Creative Center daily

---

## 🎯 Next Steps

1. **Film these concepts** (or AI-generate the videos)
2. **Test hooks** (try different openings)
3. **Track analytics** (views, saves, shares, comments)
4. **Iterate** (what works, do more of it)
5. **Scale** (post consistently, daily)

**Need help with filming or editing?**
- Use the scripts above
- AI tools: Canva, CapCut, InVideo
- Or: We can AI-generate the videos

---

**Generated:** {DATE}
**Project:** Photostudio.io
**Goal:** Brand awareness + Lead generation
**Platform:** TikTok (can repurpose to Reels, YouTube Shorts)

EOF

# Replace {DATE}
sed -i "s/{DATE}/$DATE/g" "$OUTPUT_FILE"

# Generate JSON with quick reference
cat > "$VIDEO_CONCEPTS_FILE" << 'EOF'
{
  "date": "{DATE}",
  "project": "photostudio.io",
  "platform": "tiktok",
  "concepts": [
    {
      "id": 1,
      "title": "The 'Wait, What?' Hook",
      "hook": "Watch this dress transform into 5 professional product photos in seconds...",
      "pillar": "transformation",
      "audio_suggestion": "Trending upbeat or voiceover",
      "expected_performance": "High virality, brand awareness"
    },
    {
      "id": 2,
      "title": "The Money Comparison",
      "hook": "Traditional photoshoot: €3,500. Photostudio: €35. Guess which one this is...",
      "pillar": "money_savings",
      "audio_suggestion": "Price Tag instrumental or money SFX",
      "expected_performance": "Strong for business owners, high saves"
    },
    {
      "id": 3,
      "title": "The Time-Lapse",
      "hook": "What takes 3 days in a studio... we do in 30 seconds. Watch.",
      "pillar": "time_savings",
      "audio_suggestion": "Fast-paced energetic + clock ticking",
      "expected_performance": "Appeals to time-poor entrepreneurs"
    },
    {
      "id": 4,
      "title": "The Quality Showcase",
      "hook": "People think AI photos look fake... until they see this.",
      "pillar": "quality",
      "audio_suggestion": "Myth-busting SFX, clean audio",
      "expected_performance": "Addresses objections, trust-building"
    },
    {
      "id": 5,
      "title": "The 'Behind the Scenes'",
      "hook": "Here's how we turn ONE photo into FIVE professional outputs...",
      "pillar": "education",
      "audio_suggestion": "Friendly, educational tone, lo-fi background",
      "expected_performance": "Trust-building, generates leads"
    }
  ],
  "posting_schedule": {
    "frequency": "1-2x per day",
    "best_times": ["8-10 AM", "12-2 PM", "7-9 PM"],
    "hashtag_mix": ["#ecommerce", "#productphotography", "#fashion", "#ghostmannequin", "#smallbusiness"]
  }
}
EOF

sed -i "s/{DATE}/$DATE/g" "$VIDEO_CONCEPTS_FILE"

log "  ✅ Generated 5 TikTok concepts + scripts"
log "  📄 Markdown: $OUTPUT_FILE"
log "  📊 JSON: $VIDEO_CONCEPTS_FILE"

echo "$OUTPUT_FILE"
