import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from 'react';
import { MenuIcon, XIcon } from 'lucide-react';
export function Navbar() {
    const [isOpen, setIsOpen] = useState(false);
    return (_jsx("nav", { className: "fixed top-0 left-0 right-0 z-50 bg-[#0a0e27]/90 backdrop-blur-sm border-b-2 border-[#00ff9f]/20", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 sm:px-6 lg:px-8", children: [_jsxs("div", { className: "flex items-center justify-between h-16", children: [_jsxs("a", { href: "/", className: "flex items-center gap-2 group", children: [_jsx("div", { className: "w-8 h-8 border-2 border-[#00ff9f] flex items-center justify-center group-hover:shadow-[0_0_20px_rgba(0,255,159,0.5)] transition-shadow", children: _jsx("span", { className: "text-[#00ff9f] font-bold text-sm font-mono", children: "AI" }) }), _jsx("span", { className: "text-[#e0e6ed] font-['Space_Grotesk'] font-bold text-lg tracking-tight", children: "AIMusicStore" })] }), _jsxs("div", { className: "hidden md:flex items-center gap-8", children: [_jsx("a", { href: "#discover", className: "text-[#8b9bb4] hover:text-[#00d9ff] transition-colors font-medium", children: "Discover" }), _jsx("a", { href: "#agents", className: "text-[#8b9bb4] hover:text-[#00d9ff] transition-colors font-medium", children: "Agents" }), _jsx("a", { href: "#sell", className: "text-[#8b9bb4] hover:text-[#00d9ff] transition-colors font-medium", children: "Sell Music" }), _jsx("a", { href: "#docs", className: "text-[#8b9bb4] hover:text-[#00d9ff] transition-colors font-medium", children: "Docs" })] }), _jsxs("div", { className: "hidden md:flex items-center gap-4", children: [_jsx("button", { className: "px-4 py-2 text-[#00ff9f] border-2 border-[#00ff9f] font-['Space_Grotesk'] font-semibold hover:bg-[#00ff9f]/10 hover:shadow-[0_0_20px_rgba(0,255,159,0.3)] transition-all", children: "Connect Wallet" }), _jsx("button", { className: "px-4 py-2 bg-[#00ff9f] text-[#0a0e27] font-['Space_Grotesk'] font-bold hover:shadow-[0_0_30px_rgba(0,255,159,0.5)] hover:-translate-y-0.5 transition-all", children: "Launch App" })] }), _jsx("button", { className: "md:hidden p-2 text-[#00ff9f]", onClick: () => setIsOpen(!isOpen), "aria-label": isOpen ? 'Close menu' : 'Open menu', children: isOpen ?
                                _jsx(XIcon, { className: "w-6 h-6" }) :
                                _jsx(MenuIcon, { className: "w-6 h-6" }) })] }), isOpen &&
                    _jsx("div", { className: "md:hidden border-t-2 border-[#00ff9f]/20 py-4", children: _jsxs("div", { className: "flex flex-col gap-4", children: [_jsx("a", { href: "#discover", className: "text-[#8b9bb4] hover:text-[#00d9ff] transition-colors font-medium px-2 py-2", children: "Discover" }), _jsx("a", { href: "#agents", className: "text-[#8b9bb4] hover:text-[#00d9ff] transition-colors font-medium px-2 py-2", children: "Agents" }), _jsx("a", { href: "#sell", className: "text-[#8b9bb4] hover:text-[#00d9ff] transition-colors font-medium px-2 py-2", children: "Sell Music" }), _jsx("a", { href: "#docs", className: "text-[#8b9bb4] hover:text-[#00d9ff] transition-colors font-medium px-2 py-2", children: "Docs" }), _jsxs("div", { className: "flex flex-col gap-3 pt-4 border-t border-[#00ff9f]/20", children: [_jsx("button", { className: "w-full px-4 py-3 text-[#00ff9f] border-2 border-[#00ff9f] font-['Space_Grotesk'] font-semibold", children: "Connect Wallet" }), _jsx("button", { className: "w-full px-4 py-3 bg-[#00ff9f] text-[#0a0e27] font-['Space_Grotesk'] font-bold", children: "Launch App" })] })] }) })] }) }));
}
