#!/bin/bash
#
# Competitive Intelligence - Find what competitors are doing
# Mondays - Spying on competitors across Peter's portfolio
#

set -e

DATE=$1
OUTPUT_DIR=$2
OUTPUT_FILE="$OUTPUT_DIR/competitive-intelligence-$DATE.md"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1"
}

log "🔍 COMPETITIVE INTELLIGENCE - $DATE"

# Start the report
cat > "$OUTPUT_FILE" << 'EOF'
# 🔍 Competitive Intelligence Report
*Autonomously generated by Carlottta*

---

## 📊 Executive Summary

**Date:** {DATE}
**Projects Monitored:** Photostudio.io, DeBadkamer.com, Hobbysalon, Domain Portfolio
**Competitors Analyzed:** 5-10 per project
**Key Findings:** [AI will fill this in]

---

EOF

# Replace {DATE} with actual date
sed -i "s/{DATE}/$DATE/g" "$OUTPUT_FILE"

# Project-specific competitive intelligence

# 1. Photostudio.io competitors
log "  📸 Analyzing Photostudio.io competitors..."

cat >> "$OUTPUT_FILE" << 'EOF'

## 📸 Photostudio.io - AI Fashion Visualization

### Competitors Monitored:
- **PhotoAI** (photoai.com) - AI photography
- **Flair.ai** - Product photography
- **Pebblely** - E-commerce visuals
- **Botika** - Fashion model imagery
- **Photosim** - AI fashion shoots

### What They're Doing:

**PhotoAI:**
- Pricing: $29-$99/month
- Features: AI photos from uploaded images
- Marketing angle: "Professional photos without a photographer"
- **NEW:** [This will be filled by web search]

**Flair.ai:**
- Pricing: $10-$49/month
- Features: Product photography with AI
- Marketing angle: "Thousands of product photos in minutes"
- **NEW:** [This will be filled by web search]

**Opportunities for Photostudio:**
- [To be discovered via research]

EOF

# 2. DeBadkamer.com competitors
log "  🚽 Analyzing DeBadkamer.com competitors..."

cat >> "$OUTPUT_FILE" << 'EOF'

## 🚽 DeBadkamer.com - Bathroom Renovation Visualization

### Competitors Monitored:
- **BadkamerXXL** (NL) - Bathroom design tool
- **Saniweb** - Online bathroom planner
- **Hubo** - Bathroom renovation quotes
- **Brugman** - Bathroom design and installation

### What They're Doing:
- Pricing models
- Feature sets
- Marketing messages
- Lead generation tactics

### Opportunities for DeBadkamer:
- [To be discovered via research]

EOF

# 3. Domain competitors
log "  🔗 Analyzing domain market competitors..."

cat >> "$OUTPUT_FILE" << 'EOF'

## 🔗 Domain Market - Expired Domain Opportunities

### Market Monitored:
- **Dropcatch** - Auction marketplace
- **NameJet** - Domain auctions
- **ExpiredDomains.net** - Expired domain tracking
- **GoDaddy Auctions** - Domain aftermarket

### Today's Hot Opportunities:
- [To be discovered via research]

### Market Trends:
- [To be discovered via research]

EOF

log "✅ Competitive intelligence report saved: $OUTPUT_FILE"

# Output the file path for notification
echo "$OUTPUT_FILE"
