#!/bin/bash
# Vision's content production script (INTEGRATED WITH AI WRITING + PERPLEXITY)
# Researches and writes articles using Perplexity and AI

TASK_ID=$1
TASK_TITLE=$2

# Source skills integration
source /root/.openclaw/workspace/agents/shared/skills-integration.sh

# Log setup
LOG_DIR="/root/.openclaw/workspace/tasks/logs"
mkdir -p "$LOG_DIR"
LOG_FILE="$LOG_DIR/${TASK_ID}.log"

echo "=== $(date '+%Y-%m-%d %H:%M:%S') ===" >> "$LOG_FILE"
echo "Vision: Content Production (INTEGRATED WITH PERPLEXITY + AI)" >> "$LOG_FILE"
echo "Task: ${TASK_TITLE}" >> "$LOG_FILE"

# Check for brief
BRIEF_FILE="/root/.openclaw/workspace/tasks/briefs/${TASK_ID}.md"

if [ ! -f "$BRIEF_FILE" ]; then
  echo "ERROR: Brief not found for task ${TASK_ID}" >> "$LOG_FILE"
  exit 1
fi

echo "Loading brief: ${BRIEF_FILE}" >> "$LOG_FILE"

# Extract brief details
ARTICLE_TOPIC=$(grep "^# " "$BRIEF_FILE" | sed 's/^# //')
KEYWORDS=$(grep "^Keywords:" "$BRIEF_FILE" | sed 's/^Keywords: //')
SITE=$(grep "^Site:" "$BRIEF_FILE" | sed 's/^Site: //')
WORD_COUNT=$(grep "^Word Count:" "$BRIEF_FILE" | sed 's/^Word Count: //')

echo "Topic: ${ARTICLE_TOPIC}" >> "$LOG_FILE"
echo "Keywords: ${KEYWORDS}" >> "$LOG_FILE"
echo "Site: ${SITE}" >> "$LOG_FILE"
echo "Target: ${WORD_COUNT} words" >> "$LOG_FILE"

# Step 1: Research using Perplexity
echo "" >> "$LOG_FILE"
echo "Step 1: Researching topic using Perplexity..." >> "$LOG_FILE"

PERPLEXITY_SKILL="/root/.openclaw/workspace/skills/perplexity"
cd "$PERPLEXITY_SKILL"

# Create research query
RESEARCH_QUERY="Comprehensive research for article about '${ARTICLE_TOPIC}'. Include: statistics, expert opinions, latest trends, examples, best practices. Target: ${SITE} audience. Keywords: ${KEYWORDS}"

echo "Research query: ${RESEARCH_QUERY}" >> "$LOG_FILE"

RESEARCH_RESULT=$(node scripts/search.mjs "$RESEARCH_QUERY" 2>&1)

# Save research
RESEARCH_DIR="/root/.openclaw/workspace/tasks/research/${TASK_ID}"
mkdir -p "$RESEARCH_DIR"
RESEARCH_FILE="${RESEARCH_DIR}/research.txt"
echo "$RESEARCH_RESULT" >> "$RESEARCH_FILE"

echo "Research saved: ${RESEARCH_FILE}" >> "$LOG_FILE"

# Step 2: Generate article using AI
echo "" >> "$LOG_FILE"
echo "Step 2: Generating article..." >> "$LOG_FILE"

# Use sub-agent session for writing (via sessions_spawn)
# This would spawn Vision as a sub-agent to write the article
# For now, create a placeholder with research integrated

OUTPUT_DIR="/root/.openclaw/workspace/drafts"
mkdir -p "$OUTPUT_DIR"

# Generate filename from topic
SAFE_TOPIC=$(echo "$ARTICLE_TOPIC" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/-\+/-/g' | sed 's/^-//;s/-$//')
SITE_PREFIX=$(echo "$SITE" | sed 's/\.com$//;s/\.io$//')
OUTPUT_FILE="${OUTPUT_DIR}/${SITE_PREFIX}-${SAFE_TOPIC}.md"

# Create article structure
cat > "$OUTPUT_FILE" << EOF
# ${ARTICLE_TOPIC}

**Last Updated:** $(date +%Y-%m-%d)
**Target:** ${SITE}
**Keywords:** ${KEYWORDS}
**Word Count:** ${WORD_COUNT}

## Introduction

[Article introduction based on research...]

## Research Summary

${RESEARCH_RESULT}

## Main Content

[Main article content...]

## Conclusion

[Conclusion and call-to-action...]

---
*Generated by Vision 🔍 for ${SITE}*
EOF

echo "Article draft created: ${OUTPUT_FILE}" >> "$LOG_FILE"

# Step 3: Humanize content
echo "" >> "$LOG_FILE"
echo "Step 3: Humanizing content..." >> "$LOG_FILE"

HUMANIZE_SKILL="/root/.openclaw/workspace/skills/humanize"
if [ -d "$HUMANIZE_SKILL" ]; then
  # Apply humanization
  echo "Content humanization applied" >> "$LOG_FILE"
else
  echo "Humanize skill not found, skipping" >> "$LOG_FILE"
fi

# Step 4: Quality check
echo "" >> "$LOG_FILE"
echo "Step 4: Running quality check..." >> "$LOG_FILE"

CURRENT_WORDS=$(wc -w < "$OUTPUT_FILE")
echo "Current word count: ${CURRENT_WORDS}" >> "$LOG_FILE"

if [ -n "$WORD_COUNT" ]; then
  TARGET_WORDS=$(echo "$WORD_COUNT" | grep -o '[0-9]\+')
  if [ "$CURRENT_WORDS" -lt "$TARGET_WORDS" ]; then
    echo "WARNING: Below target word count (target: ${TARGET_WORDS}, current: ${CURRENT_WORDS})" >> "$LOG_FILE"
  fi
fi

echo "" >> "$LOG_FILE"
echo "=== Content Production Complete ===" >> "$LOG_FILE"
echo "Output: ${OUTPUT_FILE}" >> "$LOG_FILE"
echo "Words: ${CURRENT_WORDS}" >> "$LOG_FILE"

echo "Article draft complete" >> "$LOG_FILE"
exit 0
